name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm run install-frontend
      - name: Unlock Environment Variables
        run: npm run unlock-frontend ${{ secrets.ENVIRONMENT_PASSWORD }}
      - name: Run Unit Tests
        run: npm run test
      - name: Build for Production
        run: npm run build
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: frontend/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: frontend/dist
      - name: Unlock Environment Variables
        run: npm run unlock-functions ${{ secrets.ENVIRONMENT_PASSWORD }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
